logging:
  level: INFO
  loggers:
    santanu: INFO

server:
  applicationConnectors:
    - type: http
      port: 80
  adminConnectors:
    - type: http
      port: 81

shortUrlPrefix: http://localhost/

redisConfig:
  hostname: localhost
  port: 6379